{
 "title": "Vulnerability Analyzer2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_stream_alive_stream_threads, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Record Consumption Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_topic_records_consumed_total{instance=\"$instance\"}[1m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Record Production Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_topic_records_produced_total{instance=\"$instance\"}[1m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Poll Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_thread_poll_rate{instance=\"$instance\"}) by (thread_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Heartbeat Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_coordinator_heartbeat_rate{instance=\"$instance\"}) by (client_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "JVM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_info_total{instance=\"$instance\"}",
     "legendFormat": "{{runtime}} {{vendor}} {{version}}"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Kafka Streams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Thread Process Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_thread_process_total{instance=\"$instance\"}[1m])) by (thread_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Process Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_thread_process_latency_avg{instance=\"$instance\"}) by (thread_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Punctuate Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_thread_punctuate_total{instance=\"$instance\"}[1m])) by (thread_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Punctuate Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_thread_punctuate_latency_avg{instance=\"$instance\"}) by (thread_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Store Get Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_state_get_rate{instance=\"$instance\"}) by (in_memory_state_id)",
     "legendFormat": "{{in_memory_state_id}} {{thread_id}}"
    }
   ]
  },
  {
   "title": "State Store Put Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_state_put_rate{instance=\"$instance\"}) by (in_memory_state_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Store Delete Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_state_delete_rate{instance=\"$instance\"}) by (in_memory_state_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "OSS Index Analyzer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Records Consumed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ossindex_records_consumed_total{instance=\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{instance=\"$instance\",clientName=\"ossindex.sonatype.org\"}[1m])) by (clientName) / sum(rate(http_client_requests_seconds_count{instance=\"$instance\",clientName=\"ossindex.sonatype.org\"}[1m])) by (clientName) >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cache_size{instance=\"$instance\",cache=\"ossindex\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Get Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(cache_gets_total{instance=\"$instance\",cache=\"ossindex\"}[1m])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Cache Put Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "rate(cache_puts_total{instance=\"$instance\",cache=\"ossindex\"}[1m])",
     "legendFormat": "Puts"
    }
   ]
  },
  {
   "title": "Retry Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(ossindex_retry_retry_total{instance=\"$instance\"}[1m])",
     "legendFormat": "{{status}} (after {{attempts}} attempts)"
    }
   ]
  },
  {
   "title": "Retry Store Entries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 68 },
   "targets": [
    {
     "expr": "ossindex_retry_store_entries{instance=\"$instance\"}",
     "legendFormat": "Task {{taskId}}"
    },
    {
     "expr": "sum(ossindex_retry_store_entries{instance=\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Batch Store Entries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 68 },
   "targets": [
    {
     "expr": "ossindex_batch_store_entries{instance=\"$instance\"}",
     "legendFormat": "Task {{taskId}}"
    },
    {
     "expr": "sum(ossindex_batch_store_entries{instance=\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Snyk Analyzer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Records Consumed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(snyk_records_consumed_total{instance=\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(httpcomponents_httpclient_request_seconds_sum{instance=\"$instance\", client=\"snykHttpClient\"}[1m])) by (client) / sum(rate(httpcomponents_httpclient_request_seconds_count{instance=\"$instance\"}[1m])) by (client) >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cache_size{instance=\"$instance\",cache=\"snyk\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Get Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(cache_gets_total{instance=\"$instance\",cache=\"snyk\"}[1m])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Cache Put Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "rate(cache_puts_total{instance=\"$instance\",cache=\"snyk\"}[1m])",
     "legendFormat": "Puts"
    }
   ]
  },
  {
   "title": "Retry Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(snyk_retry_retry_total{instance=\"$instance\"}[1m])",
     "legendFormat": "{{status}} (after {{attempts}} attempts)"
    }
   ]
  },
  {
   "title": "Retry Store Entries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 90 },
   "targets": [
    {
     "expr": "snyk_retry_store_entries{instance=\"$instance\"}",
     "legendFormat": "Task {{taskId}}"
    },
    {
     "expr": "sum(snyk_retry_store_entries{instance=\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}